Repository SFTtech/nyan, pull requests merged in 2019-10, with the labels that each got.

#67 Spec things
  README.md
  doc/nyan.md
Labels: nice new thing ☺, specification

#73 Update README.md with working freenode badge
  README.md
Labels: bugfix, documentation

#77 Fix Visual Studio build
  nyan/config.h
  nyan/error.h
  nyan/location.h
Labels: bugfix, windows

#75 Adding .travis.yml using clang for MacOSX
  .travis.yml
  README.md
Labels: buildsystem, mac os

#76 Small batch of Clang tidy fixes
  nyan/ast.cpp
  nyan/namespace.cpp
  nyan/util.cpp
Labels: c++, improvement
